#!/bin/sh

export TERMINAL="~/.local/bin/xdg-terminal-exec"
xrandr --dpi 96
remapd &
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/sxhkdrc ~/.config/sxhkd/private.sxhkd &
xsetroot -cursor_name left_ptr &
xrdb -load ~/.config/x11/xresources
xinput set-prop 12 "libinput Accel Speed" 1.0
~/.fehbg &
dunst &
pipewire &
picom --config ~/.config/picom/picom.conf &
~/.config/polybar/launch.sh &

bspc config normal_border_color "#E0E0E0"
bspc config active_border_color "#595959"
bspc config focused_border_color "#595959"
bspc config presel_feedback_color "#595959"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        1px
bspc config window_gap          5px

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
